name: Wake up Streamlit App

on:
  schedule:
    # La tarea se ejecutará a las 00:00, 06:00, 12:00, y 18:00 (UTC)
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run Python script
        run: python main.py
